# .github/labels.yml
# 既存名からのリネームは "from:" で指定（複数可）
- name: bug
  color: d73a4a
  description: Something isn't working
  from:
    - Bug
    - :bug:

- name: enhancement
  color: a2eeef
  description: New feature or request

- name: documentation
  color: 0075ca
  description: Improvements or additions to documentation

# 不要ラベルを消したい場合は後述の 'sync: true' をワークフロー側で有効化
